# .goreleaser.yml

builds:
- id: gowatch
  binary: gowatch
  main: .
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - arm

release:
  github:
    owner: teyhouse
    name: gowatch
  header: |
    ## GOWATCH ({{ .Date }})

    Attention regarding the Windows-Build: Please run this with administrative privileges!
  footer: |
    ## EOF

    Those were the changes on {{ .Tag }}!
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
  extra_files:
    - glob: ./settings.json
    - glob: ./event.json

archives:
  -
      id: gowatch
      format: zip
      rlcp: true
      files:
      - settings.json
      - event.json