# .goreleaser.yml

builds:
- id: gowatch
  binary: gowatch
  main: .
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - arm

archives:
  -
    id: my-archive
    rlcp: true
    builds:
    - default
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - settings.json
      - event.json