# .goreleaser.yml
builds:
- id: gowatch
  binary: gowatch
  main: .
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - arm
  extra_files:
    - glob: ./settings.json
    - glob: ./event.json